### ISSUE TITLE
Mirroring sometimes fails with "No such file or directory"

### ISSUE THREAD

**Issue by lagartoflojo** [SUSE/rmt#117]
From the logs of `rmt-server-mirror.service`:

```
Mar 21 02:01:47 rmt rmt-cli[3454]: Mirroring repository SLE-Module-Legacy12-Pool to /usr/share/rmt/public/repo
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:45.507740 #3454]  INFO -- : → directory.yast
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:45.692643 #3454]  INFO -- : → license.de.txt
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:46.285904 #3454]  INFO -- : → license.es.txt
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:46.745088 #3454]  INFO -- : → license.fr.txt
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:47.020948 #3454]  INFO -- : → license.it.txt
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:47.226396 #3454]  INFO -- : → license.ja.txt
Mar 21 02:01:47 rmt rmt-cli[3454]: I, [2018-03-21T02:01:47.412607 #3454]  INFO -- : → license.ko.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: /usr/share/rmt/lib/rmt/mirror.rb:125:in `initialize': No such file or directory @ rb_sysopen - /tmp/d20180321-3454-3jy31p/directory.yast (Errno::ENOENT)
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/mirror.rb:125:in `open'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/mirror.rb:125:in `mirror_license'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/mirror.rb:31:in `mirror'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/base.rb:90:in `mirror!'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/main.rb:26:in `block in mirror'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/main.rb:26:in `mirror'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/base.rb:22:in `block in dispatch'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/base.rb:33:in `handle_exceptions'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/lib/rmt/cli/base.rb:22:in `dispatch'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
Mar 21 02:04:21 rmt rmt-cli[3454]:         from /usr/share/rmt/bin/rmt-cli:40:in `<main>'
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:47.872110 #3454]  INFO -- : → license.pt_BR.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:48.319427 #3454]  INFO -- : → license.ru.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:48.508310 #3454]  INFO -- : → license.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:48.694386 #3454]  INFO -- : → license.zh_CN.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:49.148291 #3454]  INFO -- : → license.zh_TW.txt
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:49.337903 #3454]  INFO -- : → repomd.xml
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:49.787041 #3454]  INFO -- : → repomd.xml.key
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:49.971263 #3454]  INFO -- : → repomd.xml.asc
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:50.423472 #3454]  INFO -- : → a520dfc6a1381cf7a81153e26f980b7991c1204df404cc87aa0406b96ab17eed-filelists.xml.gz
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:50.870874 #3454]  INFO -- : → 79e8ba0768866d978e5f41fe1316b27f1bec76f62674ce4bc16b37880208d359-susedata.xml.gz
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:51.318416 #3454]  INFO -- : → ff2b95bddf7a2c57a0d00a631abc32f852dac0b5efd92733facab87a9a194a96-other.xml.gz
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:51.539702 #3454]  INFO -- : → 2800235d054959bc659bac62602237e6f2963a2510bf67f838985d0f64a8f638-primary.xml.gz
Mar 21 02:04:21 rmt rmt-cli[3454]: I, [2018-03-21T02:01:51.742719 #3454]  INFO -- : → a008fd6cfa7ad376aefe60eeeb77c27ace54f8fa37331e7d311b7762d6482ddb-license.tar.gz
```

**Comment by ikapelyukhin** [comment]
Interesting, I'll take a look -- maybe something's fishy about the yast metadata file.
@lagartoflojo Can the issue be isolated only this repo? Does it happen every time?

**Comment by lagartoflojo** [comment]
@ikapelyukhin I'm not sure, I didn't investigate further =/

**Comment by lagartoflojo** [comment]
This has not happened again, so it can be closed.
