### ISSUE TITLE
Some CLI shortcuts break

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#240]
1. `rmt-cli p e sles/15/x86_64` -- works.
2. `rmt-cli p l` -- breaks with:

```
Traceback (most recent call last):
	16: from /usr/bin/rmt-cli:33:in `<main>'
	15: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	14: from /usr/share/rmt/lib/rmt/cli/base.rb:29:in `dispatch'
	13: from /usr/share/rmt/lib/rmt/cli/base.rb:40:in `handle_exceptions'
	12: from /usr/share/rmt/lib/rmt/cli/base.rb:29:in `block in dispatch'
	11: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	10: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 8: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	 7: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	 6: from /usr/share/rmt/lib/rmt/cli/base.rb:29:in `dispatch'
	 5: from /usr/share/rmt/lib/rmt/cli/base.rb:40:in `handle_exceptions'
	 4: from /usr/share/rmt/lib/rmt/cli/base.rb:29:in `block in dispatch'
	 3: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:338:in `dispatch'
	 2: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:433:in `normalize_command_name'
	 1: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:453:in `find_command_possibilities'
/usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:453:in `sort': comparison of String with :ls failed (ArgumentError)
```

This mapping probably needs to be a string instead of a symbol:

https://github.com/SUSE/rmt/blob/bb928ca9b765249b0f3c05c447438c1037b141d7/lib/rmt/cli/products.rb#L36

Same for other Thor command mappings.

**Comment by tmuntaner** [comment]
@ikapelyukhin We just merged in a fix, do you mind seeing if you still have this issue?

**Comment by ikapelyukhin** [comment]
Looks good :+1:
