### ISSUE TITLE
Possible to Move/Chante rmt-server repo path ( /var/lib/rmt/public/repo )?

### ISSUE THREAD

**Issue by kevinrsalisbury** [SUSE/rmt#73]
This is not an issue. It's a usability question:
If an admin testing rmt has mirrored so many products the server is now reaching dangerous space limitations, what to do? ;-) Is it possible to safely change the path of the rmt-server mirror repo to another directory, after a one-time rsync copy to say a NFS share?

**Comment by ikapelyukhin** [comment]
Hello, Kevin. Feel free to move the directory, just create a symlink from `/var/lib/rmt/public/repo` to a new destination.

**Comment by kalabiyau** [comment]
@kevinrsalisbury if you don't mind I close this issue. If you have any questions - feel free to re-open

**Comment by kevinrsalisbury** [comment]
Ok yes, I figured that much, just wanted to make sure no know issues with nfs. I will try it and report if I find anything.

**Comment by ikapelyukhin** [comment]
Kevin,

We've implemented file de-duplication recently (sometimes some of the files in different repositories might be exactly the same -- they'll be copied/hardlinked instead of being downloaded if you already have them).

Hard links probably won't work on NFS, this is why we have implemented copying as an alternative method of de-duplication (same as SMT). Please feel free to give it a try and let us know if you have any issues.

The most recent version of the RPM package on the Build Service should contain those changes.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
@ikapelyukhin @kalabiyau

OK. What am I missing here with NFS, I must be doing something silly. rmt-cli mirror keeps failing against the NFS share. I keep running into ruby fileutils.rb errors. This time it's chmod, last time it was utime and rmdir. I have a Suse NFS4 share setup with proper user ownership and permissions on /s1-salt/public (which contains all data formerly in /var/lib/rmt/public/repo ) and it's properly symlinked to /usr/share/rmt/public. See below for details - would appreciate your thoughts;

```
server:/s1-salt/public/repo # ll /usr/share/rmt/public
lrwxrwxrwx 1 _rmt nginx 15 Jan  8 13:53 /usr/share/rmt/public -> /s1-salt/public

server:/s1-salt/public/repo # nfsidmap -c #just to be sure I pull latest idmapd info

server:/s1-salt/public/repo # rmt-cli mirror
Mirroring repository SLE-12-GA-Desktop-NVIDIA-Driver
I, [2018-01-09T07:13:36.555836 #684]  INFO -- : No product license found
I, [2018-01-09T07:13:36.564041 #684]  INFO -- : ↓ repomd.xml
I, [2018-01-09T07:13:36.568612 #684]  INFO -- : ↓ repomd.xml.key
I, [2018-01-09T07:13:36.570904 #684]  INFO -- : ↓ repomd.xml.asc
I, [2018-01-09T07:13:36.576498 #684]  INFO -- : ↓ f210b539c39142308b91f14b82200bbb5e0cc31d9ab2bb6aad2d77da3a4d9d47-filelists.xml.gz
I, [2018-01-09T07:13:36.588739 #684]  INFO -- : ↓ 1f6d42da5f7bcf8d6d1e6b1563afa5f02dbacc1b4fe45e5be6913cfaea389327-other.xml.gz
I, [2018-01-09T07:13:36.594792 #684]  INFO -- : ↓ b37db1bf66214660a90df2e0220ca726f6f0adefa662ef5ea9baffe9d9ab113e-primary.xml.gz
Mirroring repository SLED12-Updates
I, [2018-01-09T07:13:37.500767 #684]  INFO -- : No product license found
I, [2018-01-09T07:13:37.652303 #684]  INFO -- : ↓ repomd.xml
I, [2018-01-09T07:13:37.750296 #684]  INFO -- : ↓ repomd.xml.key
I, [2018-01-09T07:13:37.866559 #684]  INFO -- : ↓ repomd.xml.asc
I, [2018-01-09T07:13:37.988373 #684]  INFO -- : ↓ 22d6d2f71aeec90886fecefddb922606e0dff9aafef4595277e73c99e3af4aec-app-icons.tar.gz
I, [2018-01-09T07:13:38.321305 #684]  INFO -- : ↓ 14cf21691cd88a1585c7ca90de15156eb1891b2f5b99013abce60ae80dfc0602-appdata.xml.gz
I, [2018-01-09T07:13:38.781900 #684]  INFO -- : ↓ 7236ef6e2c96ed829a873817cce7ca080ac1cd383ce179256b8a1da202bab18e-filelists.xml.gz
I, [2018-01-09T07:13:39.121694 #684]  INFO -- : ↓ ec8cb7bb9a44f2c209ec7199cb2aceb06eade95a0124a1ced8d1807bd2fea7e0-updateinfo.xml.gz
I, [2018-01-09T07:13:39.386204 #684]  INFO -- : ↓ 1ec82d0459eed630d3ace468c116f6e7fd4041c0c7c8c6853f7b64079f7bae8d-primary.xml.gz
I, [2018-01-09T07:13:39.509802 #684]  INFO -- : ↓ 1476938f98489dfb3fddfe05b960ef5a01c4bdbcfc2c247eb974b1bcd656e7a1-susedata.xml.gz
I, [2018-01-09T07:13:39.711083 #684]  INFO -- : ↓ cfde01d33c6118567d8d9432c9ec3e2ac80d07a43b068cdbf01cc82b955707f8-other.xml.gz
I, [2018-01-09T07:13:39.865927 #684]  INFO -- : ↓ fcd35ed009ff0b4550fdc6246a69cfd7ac162260ff31e6150bdbbbdfefc0739f-deltainfo.xml.gz
Mirroring repository SLED12-Pool
/usr/lib64/ruby/2.4.0/fileutils.rb:1320:in `chmod': Operation not permitted @ chmod_internal - /usr/share/rmt/public/repo/SUSE/Products/SLE-DESKTOP/12/x86_64/product/../product.license/directory.yast (Errno::EPERM)
	from /usr/lib64/ruby/2.4.0/fileutils.rb:1320:in `copy_metadata'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:418:in `block in copy_entry'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:1393:in `wrap_traverse'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:412:in `copy_entry'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:470:in `rescue in block in mv'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:467:in `block in mv'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:1460:in `block in fu_each_src_dest'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:1476:in `fu_each_src_dest0'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:1458:in `fu_each_src_dest'
	from /usr/lib64/ruby/2.4.0/fileutils.rb:457:in `mv'
	from /usr/share/rmt/lib/rmt/downloader.rb:124:in `make_request'
	from /usr/share/rmt/lib/rmt/downloader.rb:30:in `block in download'

```
